
CMD(hlt,  hlt(&number))
CMD(push, push(&my_cpu,&number))
CMD(mul,  mul(&my_cpu.stack_cpu))
CMD(pop,  pop(&my_cpu, &number))
CMD(add,  add(&my_cpu.stack_cpu))
CMD(div,  div(&my_cpu.stack_cpu))
CMD(out,  out(&my_cpu.stack_cpu))
CMD(sub,  sub(&my_cpu.stack_cpu))
CMD(db,   db(&my_cpu, &number))
CMD(jmp,  jmp(&my_cpu, &number))
CMD(jb,   jb(&my_cpu, &number))
CMD(jbe,  jbe(&my_cpu, &number))
CMD(ja,   ja(&my_cpu, &number))
CMD(jae,  jae(&my_cpu, &number))
CMD(je,   je(&my_cpu, &number))
CMD(jne,  jne(&my_cpu, &number))
CMD(call, call(&my_cpu, &number, &addresses_for_call))
CMD(in,   in(&my_cpu.stack_cpu, &number))
CMD(ret,  ret(&addresses_for_call, &number))
CMD(print, print(&my_cpu))
CMD(label, ;)
CMD(meow, meow())
CMD(sqrt, sqrt(&my_cpu.stack_cpu))
CMD(sum,  sum(&my_cpu.stack_cpu))
CMD(video, video(&my_cpu))